name: Build Release Packages

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI
  release:
    types: [created]  # Triggers when a new release is created

jobs:
  build-zips:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Extract version from tag
      id: get_version
      run: |
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
          # Remove 'v' prefix if present (e.g., v1.0.0 -> 1.0.0)
          VERSION=${VERSION#v}
        else
          # Default version if not a tag (for manual/PR builds)
          VERSION="1.0.0"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version: $VERSION (folder structure only, files not modified)"
    
    - name: Setup build directory structure
      run: |
        VERSION="${{ steps.get_version.outputs.version }}"
        mkdir -p "dist/v${VERSION}"
        echo "Building version: v${VERSION}"
    
    - name: Build zip for OpenCart 1.5.x
      run: |
        VERSION="${{ steps.get_version.outputs.version }}"
        mkdir -p "dist/v${VERSION}/opencart-1.5"
        cd 1.5/upload
        zip -r "../../dist/v${VERSION}/opencart-1.5/chip.ocmod.zip" .
    
    - name: Build zip for OpenCart 2.0.x & 2.1.x
      run: |
        VERSION="${{ steps.get_version.outputs.version }}"
        mkdir -p "dist/v${VERSION}/opencart-2.0"
        cd 2.0/upload
        zip -r "../../dist/v${VERSION}/opencart-2.0/chip.ocmod.zip" .
    
    - name: Build zip for OpenCart 2.2.x
      run: |
        VERSION="${{ steps.get_version.outputs.version }}"
        mkdir -p "dist/v${VERSION}/opencart-2.2"
        cd 2.2/upload
        zip -r "../../dist/v${VERSION}/opencart-2.2/chip.ocmod.zip" .
    
    - name: Build zip for OpenCart 2.3.x
      run: |
        VERSION="${{ steps.get_version.outputs.version }}"
        mkdir -p "dist/v${VERSION}/opencart-2.3"
        cd 2.3/upload
        zip -r "../../dist/v${VERSION}/opencart-2.3/chip.ocmod.zip" .
    
    - name: Build zip for OpenCart 3.0.x
      run: |
        VERSION="${{ steps.get_version.outputs.version }}"
        mkdir -p "dist/v${VERSION}/opencart-3.0"
        cd 3.0/upload
        zip -r "../../dist/v${VERSION}/opencart-3.0/chip.ocmod.zip" .
    
    - name: Build zip for OpenCart 4.0.x
      run: |
        VERSION="${{ steps.get_version.outputs.version }}"
        cd 4.0
        mkdir -p "../dist/v${VERSION}/opencart-4.0"
        zip -r "../dist/v${VERSION}/opencart-4.0/chip.ocmod.zip" . -x "README.md"
    
    - name: Build zip for OpenCart 4.1.x
      run: |
        VERSION="${{ steps.get_version.outputs.version }}"
        cd 4.1
        mkdir -p "../dist/v${VERSION}/opencart-4.1"
        zip -r "../dist/v${VERSION}/opencart-4.1/chip.ocmod.zip" . -x "README.md"
    
    - name: Create master zip file
      run: |
        VERSION="${{ steps.get_version.outputs.version }}"
        cd dist
        zip -r "chip-for-opencart-v${VERSION}.zip" "v${VERSION}"
        echo "Created master zip: chip-for-opencart-v${VERSION}.zip"
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: chip-opencart-extensions
        path: dist/chip-for-opencart-*.zip
        retention-days: 90
    
    - name: Upload to release (if tag exists)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/chip-for-opencart-*.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

